FROM apache/airflow:2.7.2-python3.12
WORKDIR /opt/airflow

COPY airflow/requirements-airflow.txt .
RUN pip install --no-cache-dir -r requirements-airflow.txt

COPY airflow/dags /opt/airflow/dags

CMD ["airflow", "standalone"]
