FROM apache/airflow:2.10.4-python3.8
WORKDIR /opt/airflow

COPY airflow/requirements-airflow.txt .
RUN pip install --no-cache-dir -r requirements-airflow.txt

# COPY airflow/dags /opt/airflow/dags

# CMD ["airflow", "standalone"]
CMD ["bash"]
