FROM python:3.12-slim
WORKDIR /app

COPY api/requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

# sub-modules imports needs this architecture
COPY api/ /app/api/

# date_randomseed sub module
COPY date_randomseed/ /app/date_randomseed/

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
