FROM python:3.12-slim
WORKDIR /app/api

COPY api/requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY api/ .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
