FROM python:3.12-slim
WORKDIR /app

COPY extract/requirements-etl_extract.txt .
RUN pip install --no-cache-dir -r requirements-etl_extract.txt

COPY extract/extract.py /app/extract/extract.py

# date_randomseed sub module
COPY date_randomseed/ /app/date_randomseed/

CMD ["python3", "-m extract.extract"]
