FROM apache/airflow:2.10.4-python3.8
WORKDIR /opt/airflow

# Crée un répertoire pour stocker le cache pip (re-build images faster)
RUN mkdir -p /home/airflow/.cache/pip

COPY airflow/requirements-airflow.txt .
# RUN pip install --no-cache-dir -r requirements-airflow.txt
RUN pip install -r requirements-airflow.txt --cache-dir=/home/airflow/.cache/pip

# COPY airflow/dags /opt/airflow/dags

# CMD ["airflow", "standalone"]
# CMD ["bash"]
