steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-repo/api:latest',
        './api'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-repo/api:latest'
      ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-repo/api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
