name: Python Lint and Format

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Python code with Pylint and format with Black
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies (Black and Pylint)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint

      # Step 4: Lint Python code with Pylint
      - name: Run Pylint
        run: |
          pylint **/*.py --max-line-length=120  # Optional: adjust according to your style

      # Step 5: Format code with Black (check only, no auto-formatting)
      - name: Run Black formatter
        run: |
          black --check .  # Check if code is formatted, without modifying the code
